import React from 'react'
import Head from 'next/head'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
import ContentMain from '../components/ContentMain'
import ContentExperience from '../components/ContentExperience'
import ContentWork from '../components/ContentWork'
import ContentContact from '../components/ContentContact'

export default function Home() {
  return (
    <div className={styles.container} style={{scrollBehavior:'smooth'}}>
      <Head>
        <title>Dave Lopper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ContentMain />
      <ContentExperience />
      <ContentWork/>
      <ContentContact />
    </div>
  )
}
